# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: core.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'core.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ncore.proto\x12\x12streetcred.core.v1\"H\n\x11MovePlayerRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x10\n\x08target_x\x18\x02 \x01(\x05\x12\x10\n\x08target_y\x18\x03 \x01(\x05\"6\n\x12MovePlayerResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"/\n\x19RollbackPvPSessionRequest\x12\x12\n\nsession_id\x18\x01 \x01(\x05\">\n\x1aRollbackPvPSessionResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x7f\n\tGameEvent\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x11\n\tplayer_id\x18\x02 \x01(\t\x12\x0e\n\x06\x61mount\x18\x03 \x01(\r\x12\r\n\x05\x62\x61\x64ge\x18\x04 \x01(\t\x12\x0e\n\x06streak\x18\x05 \x01(\r\x12\x11\n\ttimestamp\x18\x06 \x01(\t\x12\x0f\n\x07payload\x18\x07 \x01(\t2\xdf\x01\n\x0b\x43oreService\x12[\n\nMovePlayer\x12%.streetcred.core.v1.MovePlayerRequest\x1a&.streetcred.core.v1.MovePlayerResponse\x12s\n\x12RollbackPvPSession\x12-.streetcred.core.v1.RollbackPvPSessionRequest\x1a..streetcred.core.v1.RollbackPvPSessionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'core_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MOVEPLAYERREQUEST']._serialized_start=34
  _globals['_MOVEPLAYERREQUEST']._serialized_end=106
  _globals['_MOVEPLAYERRESPONSE']._serialized_start=108
  _globals['_MOVEPLAYERRESPONSE']._serialized_end=162
  _globals['_ROLLBACKPVPSESSIONREQUEST']._serialized_start=164
  _globals['_ROLLBACKPVPSESSIONREQUEST']._serialized_end=211
  _globals['_ROLLBACKPVPSESSIONRESPONSE']._serialized_start=213
  _globals['_ROLLBACKPVPSESSIONRESPONSE']._serialized_end=275
  _globals['_GAMEEVENT']._serialized_start=277
  _globals['_GAMEEVENT']._serialized_end=404
  _globals['_CORESERVICE']._serialized_start=407
  _globals['_CORESERVICE']._serialized_end=630
# @@protoc_insertion_point(module_scope)
