# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: core.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'core.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ncore.proto\x12\x12streetcred.core.v1\"H\n\x11MovePlayerRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x10\n\x08target_x\x18\x02 \x01(\x05\x12\x10\n\x08target_y\x18\x03 \x01(\x05\"6\n\x12MovePlayerResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2j\n\x0b\x43oreService\x12[\n\nMovePlayer\x12%.streetcred.core.v1.MovePlayerRequest\x1a&.streetcred.core.v1.MovePlayerResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'core_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MOVEPLAYERREQUEST']._serialized_start=34
  _globals['_MOVEPLAYERREQUEST']._serialized_end=106
  _globals['_MOVEPLAYERRESPONSE']._serialized_start=108
  _globals['_MOVEPLAYERRESPONSE']._serialized_end=162
  _globals['_CORESERVICE']._serialized_start=164
  _globals['_CORESERVICE']._serialized_end=270
# @@protoc_insertion_point(module_scope)
