use tonic::{transport::Server, Request, Response, Status};
use tracing::{info, error};
use anyhow::Result;
use std::sync::Arc;
use tokio::sync::Mutex;
use anyhow::Context;
use dotenvy::dotenv;

// Local modules
mod config;
mod health;

// New modular structure
mod game_engine;
mod infra;
mod events;

use config::Config;
use health::HealthChecker;
use infra::starknet::StarknetClient;
use infra::db::Database;
use game_engine::game_engine::{GameEngine, MoveData};
use game_engine::tile::TileService;
use game_engine::streak::StreakService;
use game_engine::pvp::PvPService;
use game_engine::rewards::RewardService;
use game_engine::dispatcher::{CompositeDispatcher, WebSocketEventDispatcher};
use game_engine::scheduler::StreakScheduler;
use game_engine::streak::StreakManager;
use infra::KafkaEventDispatcher;

// This module is auto-generated by `tonic-build` from our .proto file.
pub mod core {
    tonic::include_proto!("streetcred.core.v1");
}

use core::core_service_server::{CoreService as GrpcCoreService, CoreServiceServer};
use core::{MovePlayerRequest, MovePlayerResponse, RollbackPvPSessionRequest, RollbackPvPSessionResponse};

// Define our service struct
pub struct MyCoreService {
    game: Arc<GameEngine>,
}

// Implement the gRPC service trait for our struct
#[tonic::async_trait]
impl GrpcCoreService for MyCoreService {
    // Implement the `move_player` RPC method
    async fn move_player(
        &self,
        request: Request<MovePlayerRequest>,
    ) -> Result<Response<MovePlayerResponse>, Status> {
        let req = request.into_inner();
        info!("Received move_player request for user_id: {}", req.user_id);
        let move_data = MoveData {
            target_x: req.target_x,
            target_y: req.target_y,
        };
        match self.game.process_move(req.user_id, move_data).await {
            Ok(summary) => {
                let response = MovePlayerResponse {
                    success: true,
                    message: format!("Move processed. Ink: {}, NFT: {}, Streak: {}", summary.ink, summary.nft_minted, summary.streak_updated),
                };
                Ok(Response::new(response))
            }
            Err(e) => {
                error!("Failed to process move_player: {}", e);
                Err(Status::internal("Failed to process move request."))
            }
        }
    }

    async fn rollback_pv_p_session(
        &self,
        request: Request<RollbackPvPSessionRequest>,
    ) -> Result<Response<RollbackPvPSessionResponse>, Status> {
        let req = request.into_inner();
        info!("Received rollback_pv_p_session request for session_id: {}", req.session_id);
        
        // TODO: Implement PvP session rollback logic
        let response = RollbackPvPSessionResponse {
            success: true,
            message: format!("PvP session {} rolled back successfully", req.session_id),
        };
        Ok(Response::new(response))
    }
}

impl MyCoreService {
    async fn new(config: Config) -> Result<Self> {
        info!("[MyCoreService::new] Entered");
        // Validate configuration
        config.validate()?;
        info!("[MyCoreService::new] Config validated");
        let config = Arc::new(config);
        // Initialize health checker
        info!("[MyCoreService::new] Initializing health checker");
        let health_checker = Arc::new(Mutex::new(
            HealthChecker::new(config.starknet_rpc_url.clone())?
        ));
        info!("[MyCoreService::new] Health checker initialized");
        // Initialize Starknet client
        info!("[MyCoreService::new] Initializing Starknet client");
        let starknet_client = StarknetClient::new(config.clone()).await?;
        info!("[MyCoreService::new] Starknet client initialized");
        // Initialize database
        info!("[MyCoreService::new] Initializing database");
        let db_url = std::env::var("DATABASE_URL")?;
        let db = Database::new(&db_url).await?;
        info!("[MyCoreService::new] Database initialized");
        // Initialize Kafka event dispatcher
        info!("[MyCoreService::new] Initializing Kafka event dispatcher");
        let kafka_dispatcher = Arc::new(KafkaEventDispatcher::new("localhost:9092")?);
        info!("[MyCoreService::new] Kafka event dispatcher initialized");
        // Initialize WebSocket event dispatcher (Redis pub/sub)
        info!("[MyCoreService::new] Initializing WebSocket event dispatcher");
        let redis_url = std::env::var("REDIS_URL").ok();
        let ws_dispatcher = Arc::new(WebSocketEventDispatcher::new(redis_url)?);
        info!("[MyCoreService::new] WebSocket event dispatcher initialized");
        // Composite dispatcher
        info!("[MyCoreService::new] Initializing CompositeDispatcher");
        let composite_dispatcher = Arc::new(CompositeDispatcher::new(vec![kafka_dispatcher.clone(), ws_dispatcher.clone()]));
        info!("[MyCoreService::new] CompositeDispatcher initialized");
        // Initialize Game logic
        info!("[MyCoreService::new] Initializing game logic services");
        let conquest = TileService::new();
        let streaks = StreakService::new(composite_dispatcher.clone());
        let pvp = PvPService::new();
        let rewards = RewardService::new(composite_dispatcher.clone());
        let game = Arc::new(GameEngine::new(
            composite_dispatcher.clone(),
            starknet_client,
            (*kafka_dispatcher).clone(),
            conquest,
            streaks,
            pvp,
            rewards,
            db.clone(),
        ));
        info!("[MyCoreService::new] GameEngine initialized");

        // Initialize streak monitoring scheduler
        info!("[MyCoreService::new] Initializing streak scheduler");
        let streak_manager = Arc::new(tokio::sync::Mutex::new(StreakManager::new()));
        let streak_scheduler = Arc::new(StreakScheduler::new(
            streak_manager,
            db,
            composite_dispatcher,
        ));
        
        // Spawn the background task for streak monitoring
        let _scheduler_handle = streak_scheduler.spawn_background_task();
        info!("[MyCoreService::new] Streak scheduler initialized and started");

        info!("[MyCoreService::new] Core service initialized successfully");
        Ok(Self { game })
    }
}

fn get_app_mode() -> String {
    std::env::var("APP_MODE").unwrap_or_else(|_| "mock".to_string())
}

fn main() {
    // Load environment variables from .env or .env.test
    dotenv().ok();
    println!("[main] Entered main");
    let app_mode = get_app_mode();
    println!("[Startup] Running in {} mode", app_mode);
    if app_mode == "mock" {
        // Use mock services here
    }
    println!("[main] Before creating tokio runtime");
    let rt = tokio::runtime::Runtime::new().unwrap();
    println!("[main] After creating tokio runtime, before block_on");
    if let Err(e) = rt.block_on(async_main()) {
        eprintln!("Application error: {}", e);
        std::process::exit(1);
    }
    println!("[main] After block_on(async_main)");
}

async fn async_main() -> Result<(), Box<dyn std::error::Error>> {
    // Load environment variables from .env or .env.test (redundant but safe for async context)
    dotenv().ok();
    println!("[async_main] Entered async_main");
    // Load configuration from environment variables
    let config = match Config::from_env().context("Failed to load configuration from environment") {
        Ok(cfg) => {
            println!("[async_main] Loaded config from env");
            info!("[async_main] Loaded config from env");
            cfg
        },
        Err(e) => {
            println!("[async_main] Failed to load config: {}", e);
            error!("[async_main] Failed to load config: {}", e);
            return Err(e.into());
        }
    };
    
    // Set up logging
    println!("[async_main] Before logging init");
    tracing_subscriber::fmt()
        .with_max_level(tracing::Level::INFO)
        .init();
    println!("[async_main] After logging init");
    info!("[async_main] Logging initialized");
    
    // Create an instance of our service
    println!("[async_main] Before creating MyCoreService");
    let core_service = match MyCoreService::new(config).await {
        Ok(svc) => {
            println!("[async_main] MyCoreService created successfully");
            info!("[async_main] MyCoreService created successfully");
            svc
        },
        Err(e) => {
            println!("[async_main] Failed to create MyCoreService: {}", e);
            error!("[async_main] Failed to create MyCoreService: {}", e);
            return Err(e.into());
        }
    };
    
    println!("[async_main] Before parsing addr");
    let addr = "0.0.0.0:50051".parse()?;
    println!("[async_main] After parsing addr: {:?}", addr);
    info!("[async_main] Core service listening on {}", addr);
    
    // Start the gRPC server
    println!("[async_main] Before starting gRPC server");
    Server::builder()
        .add_service(CoreServiceServer::new(core_service))
        .serve(addr)
        .await?;
    println!("[async_main] After gRPC server");
    
    Ok(())
}